urls.py
from django.urls import path
from . import views

app_name = 'financas'
urlpatterns = [
    # ex.:/
    path('', views.index, name='index'),
    path(
        'financas/<int:balanco_id>/',
        views.detalhes,
        name='detalhes'),

    path('financas/login/', views.Login.as_view(), name='Login'),
    path('financas/signup/', views.Cadastrar.as_view(), name='Cadastrar'),
    path('financas/logout/', views.Logout, name='Logout'),
]

models.py
from django.db import models

class Titulo(models.Model):
    text = models.CharField(max_length = 50)
    def __str__(self):
        return self.text

class Receita(models.Model):
    text = models.CharField(max_length = 200)
    valor = models.IntegerField('Receita mensal', null=True)
    titulo = models.ForeignKey(Titulo, on_delete = models.CASCADE)
    def __str__(self):
        return self.text


class Despesa(models.Model):
    text = models.CharField(max_length = 50)
    valor = models.IntegerField('Despesa mensal', null=True)
    titulo = models.ForeignKey(Titulo, on_delete = models.CASCADE)
    def __str__(self):
        return self.text

class Balanco(models.Model):
    text = models.CharField(max_length = 50)
    receitas = models.ManyToManyField(Receita)
    despesas = models.ManyToManyField(Despesa)
    valor_receita = property(lambda self: sum( rct.valor for rct in self.receitas.all() ))
    valor_despesa = property(lambda self: sum( dps.valor for dps in self.despesas.all() ))
    titulo = models.ForeignKey(Titulo, on_delete = models.CASCADE)
    def __str__(self):
        return self.text
    @property
    def valor_total(self):
        total = self.valor_receita - self.valor_despesa
        return total

class Usuario(models.Model):
    nomeuser = models.CharField(max_length=25)
    senha = models.CharField(max_length=25)
    class Meta:
        verbose_name = 'usuário'
    def __str__(self):
        return self.nomeuser

views.py
from django.shortcuts import get_object_or_404, render
from django.views import View

from .models import Receita, Despesa, Balanco, Titulo, Usuario

def index(request):
    lista_receita = Receita.objects.all()[:25]
    lista_despesa = Despesa.objects.all()[:25]
    lista_balanco = Balanco.objects.all()[:25]
    lista_titulo = Titulo.objects.all()[:25]
    context = {
        "lista_receita": lista_receita,
        "lista_despesa": lista_despesa,
        "lista_balanco": lista_balanco,
        "lista_titulo": lista_titulo,
        }
    return render(request, 'financas/index.html', context)

def detalhes (request, balanco_id):
    titulo = get_object_or_404(Titulo, pk = balanco_id)
    return render(request, 'financas/detalhes.html', {'titulo': titulo})

class Login(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'financas/index.html')
    def post(self, request, *args, **kwargs):
        user = get_object_or_404(Usuario, usuario=request.POST['username'])
        if user.senha != request.POST['password']:
            return render(request, 'financas/index.html')
        request.session['id_user'] = user.id
        return render(request, 'financas/detalhes.html')

class Cadastrar(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'financas/index.html')
    def post(self, request, *args, **kwargs):
        usuario = Usuario(usuario = request.POST['user'], senha = request.POST['password'])
        usuario.save()
        request.session['id_user'] = usuario.id
        return render(request, 'financas/detalhes.html')

def Logout(request):
    del request.session['id_user']
    return render(request, 'financas/index.html')

templates/financas/base.html
{% load static %}
<html>
    <head>
        <title>{% block titulo %}Gerenciamento das suas Finanças!{% endblock %}</title>
    </head>
    <body>
        <h1>
            Finanças Pessoais
        </h1>
        <h2>{% block titulo_pagina %}{% endblock %}</h2>

        {% block conteudo %}{% endblock %}

        {% block menu %}
        <a class="btn" role="button" href="/admin">Administração</a>
        <a class="btn btn-outline-primary" role="button"
            href="{% url 'financas:index' %}">Principal</a>
        {% endblock %}
    </body>
</html>

templates/financas/detalhes.html
<html>
    <head>
        <title>Finanças Pessoais</title>
    </head>
    <body>
        <h1>
            Finanças Pessoais
        </h1>
        <h2>{{ titulo.text | upper }}</h2>
        <h3>Lista das receitas cadastradas:</h3>
        {% if msg_erro %}
            <hr/>
            <b>{{ msg_erro }}</b>
            <hr/>
        {% endif %}
        <ul>
        {% for receita in titulo.receita_set.all %}
            {{ receita.text | truncatewords:11 }} - {{ receita.valor | truncatewords:11 }} <br>
        {% endfor %}
        </ul>
        <br>

        <h3>Lista das despesas cadastradas:</h3>

        <ul>
            {% for despesa in titulo.despesa_set.all %}
                {{ despesa.text | truncatewords:11 }} - {{ despesa.valor | truncatewords:11 }} <br>
            {% endfor %}
        </ul>

        <br>

        <h3>Balanço mensal:</h3>

        <ul>
            {% for balanco in titulo.balanco_set.all %}
                <li> <p>Valor total da receita - {{ balanco.valor_receita | truncatewords:11 }}</p> </li>
                <li> <p>Valor total da despesa - {{ balanco.valor_despesa | truncatewords:11 }}</p> </li>
                <li> <p>Valor total que sobrou - {{ balanco.valor_total | truncatewords:11 }}</p> </li>
            {% endfor %}
        </ul>

        <br>

        <a class="btn" role="button" href="/admin">Administração</a>
        <a class="btn btn-outline-primary" role="button"
            href="{% url 'financas:index' %}">Principal</a>

    </body>
</html>

templates/financas/index.html
<html>
    <head>
        <title>Finanças Pessoais</title>
    </head>
    <body>
        <h1>
            Finanças Pessoais
        </h1>
        <h2>Balancete mensal:</h2>

        {% if lista_titulo %}
        <ul>
        {% for titulo in lista_titulo %}
            <li>
                <a href=
                    "{% url 'financas:detalhes' titulo.id %}">{{ titulo.text | truncatewords:11 }}</a>
            </li>
        {% endfor %}
        </ul>
        {% else %}
            <h3>Nenhum balanco cadastrada até o momento!</h3>
        {% endif %}

        <br>

        <a class="btn" role="button" href="/admin">Administração</a>
        <a class="btn btn-outline-primary" role="button" href="{% url 'financas:index' %}">Principal</a>

    </body>
</html>